language: node_js
node_js:
- '8'
install:
- yarn add global eslint
- yarn add global babel-eslint
- yarn add global eslint-plugin-react
- yarn add global eslint-plugin-mocha
- yarn add global eslint-config-synacor
- yarn add global firebase-tools
script:
- yarn run lint
- yarn run test
- yarn run build
- gulp release
cache: yarn
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: Qa/kVi1uJKNtpz01OCbML4D+Hck2MBfU9BX7Vzs4gO95YRbz/t/Qh0qNU8JcvlDbiPZRsSmAyX/VW5HeJ9+FLb46eOHyiXQZwbSP5guMj2Hh2vc23XfB/lHEeziVjKR2HUVNcuYyN42XT11j9OVBUu1yBNO4a1iV2XoR0aVp9OX05InQoUqMFomyUaOOXHqutiokE0xdcWJyhSLW+B8zOpW5PJucmAPQaQBDdESkKc4SEKVvKG+EhxaOfTjJH9hOn1n+6UoWqqHNj7JLeJkiXTku+FWuvUUCB2uq70FuRZLLi78PgE6xRC7nRM1Ko1at93uhVOF1HgIbaXy+Ff7YJLocUECvZ58DzAUTiTRuNpV+zze+89e+YnbNUDMrnZwOK3GmYmyiNEkjIekjW7A2xeHsISQxq7CS9xqXtYDj1GK6HBXZYC9H70AJNZmO3+zS5oKrUuWvbYo0Y4KPyl9uuh9ijcyzmzpwVG79p7qpQVRVrIZ2TncVWfY9TodpP8jQMTwgH8uuWgZrdYHSOnUrqQB7E/IlvxWXA0VApGB0K8XOUS4CPWzOtlJDsndLbaR6UoCMInxQjun9fMFqulqr8vti4hNmNWN/hoBjj4rz8yENo7FBzNrgEjvtUhHffUTY901iUJP/CRg8R+u2wVD4DCWFVjeWveQfk2ysUHm5buI=
    project: staging-zenuml
  - provider: s3
    skip_cleanup: true
    bucket: staging.zenuml.com
    local_dir: app
    access_key_id: AKIAJIJNJNJBW2C367LQ
    secret_access_key:
      secure: sIeg3/K1WOODR/3p6Bf45HtWLm4fHGQXMiOpKlNM6gS1H+x8pvou1FQgR8wx0BhGwJ34goC47Yxv3C8zFLGkIkLqZIq5v6ncRi6IDjjgJfOJlTY+PzE9huCmwWKYa0iRr1WMflXulvYjk3FoeKrnDSQhJNXzSJnvU/eTcmGzVbiEQxtxYGIIUSeGat7JM5QgSLsuQ1bJ5Rc79y5nxA2FUu4Pp+553oqcY/1nTNeUXs7N1V9CzI8mpJ9PqVqEtfJx29nymUJx2YLnqzdAH3cMw7www6mmX4FW4KuZmEtxkDLmmOWyCmouq8fbiEnfQOgDL2c6MEG/EpdrCyR+ykTQ7YVVJ8kSMx+78rYtiU4tvgy0MwwfbnTbMyJ7NP34xG2goqmO+cjkc1gxtCzPVkB1zxrcwJCPmzaDafwaFnlwwrveEaZOwVLiYD15FR4TJUV8AIJr+apjB0H5NeV+CciWxm4tZCn3g3eVCPpCWtNw+xcfi6ckrjLhsRLyvlJAlMXLm061Av62hQxhKMKGcdNQ0IrgqGY3YHtZtOjWUVglAqDwvF90vbzbUQ3cf4mduupcw2TH6zYuQzsWiRPnxZL/nunZ0cE6YxuxxMfOkBcLCJEutUSZLpXjjpNRyucXD2fEZTsnb3FQQVzzQP7LMcwK2/ZRdc5idawzbwyyqSm06IA=
